# Generated by Django 6.0 on 2025-12-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OMSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Your Brand Name', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('footer_text', models.CharField(default='Thank you for using OMS SaaS', max_length=200)),
                ('dark_mode_enabled', models.BooleanField(default=False)),
                ('whatsapp_token', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_api_url', models.URLField(blank=True, null=True)),
                ('rounding_enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
